app/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('activate/<uuid:username>/', views.UserActivateView.as_view(), name='activate')


]

app/currency/urls.py
from django.urls import path
# from currency.views import contact_us_list
from app.currency import views

app_name = 'currency'

urlpatterns = [
    # path('rate/table/', rate_table),
    path('contactus/list/', views.ContactUsView.as_view(), name='contactus_list'),
    path('rate/list/', views.RateListView.as_view(), name='rate_list'),
    path('rate/create/', views.RateCreateView.as_view(), name='rate_create'),
    path('rate/update/<int:pk>/', views.RateUpdateView.as_view(), name='rate_update'),
    path('rate/delete/<int:pk>/', views.RateDeleteView.as_view(), name='rate_delete'),
    path('rate/details/<int:pk>/', views.RateDetailsView.as_view(), name='rate_details'),
    path('source/list/', views.SourceListView.as_view(), name='source_list'),
    path('source/create/', views.SourceCreateView.as_view(), name='source_create'),
    path('source/update/<int:pk>/', views.SourceUpdateView.as_view(), name='source_update'),
    path('source/details/<int:pk>/', views.SourceDetailsView.as_view(), name='source_details'),
    path('source/delete/<int:pk>/', views.SourceDeleteView.as_view(), name='source_delete'),
    path('contactus/create/', views.ContactUsCreateView.as_view(), name='contactus_create'),
    path('my-profile/', views.UserProfileView.as_view(), name='my_profile'),
    # path('change/password/', views.UserPasswordChangeView.as_view(), name='change_password'),
    # path('change/password/done/', views.UserPasswordChangeDoneView.as_view(), name='change_password_done'),


]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from app.currency import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('silk/', include('silk.urls', namespace='silk')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.v1.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from datetime import datetime
from django.db import models
from currency.model_choices import CurrencyType


class ContactUs(models.Model):
    email_from = models.EmailField(max_length=254)
    email_to = models.EmailField(max_length=254)
    subject = models.CharField(max_length=254)
    message = models.CharField(max_length=10_000)
    create = models.DateTimeField(auto_now_add=True)


def source_avatar(instance, filename):
    return 'source_avatar/{0}/{1}'.format(instance.id, filename)


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    bank_avatar = models.FileField(upload_to=source_avatar, default='bank.jpeg')


class Rate(models.Model):
    base_currency_type = models.CharField(max_length=3, choices=CurrencyType.choices,
                                          default=CurrencyType.CURRENCY_TYPE_UAH)
    currency_type = models.CharField(max_length=3, choices=CurrencyType.choices, null=True)
    sale = models.DecimalField(max_digits=10, decimal_places=4)
    buy = models.DecimalField(max_digits=10, decimal_places=4, null=True)
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE)
    created = models.DateTimeField(default=datetime.now)


class ResponseLog(models.Model):
    response_time = models.FloatField(max_length=10)
    request_method = models.CharField(max_length=12)
    query_params = models.CharField(max_length=20)
    ip = models.CharField(max_length=100)

app/currency/forms.py
from django import forms
from currency.models import Rate, Source, ContactUs


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'base_currency_type',
            'currency_type',
            'sale',
            'buy',
            'source',
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            "source_url",
            "name",
            'bank_avatar'
        )


class ContactusForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'email_from',
            'email_to',
            'subject',
            'message',
        )

app/currency/views.py
# from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from currency.filters import RateFilter
from currency.models import ContactUs, Rate, Source
from currency.forms import RateForm, SourceForm, ContactusForm
from django.views import generic
from django.urls import reverse_lazy
from django_filters.views import FilterView

from app.currency.tasks import send_contactus_mail


class IndexView(generic.TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rate_count'] = Rate.objects.count()
        context['source_count'] = Source.objects.count()
        return context


class ContactUsView(generic.ListView):
    queryset = ContactUs.objects.all()
    template_name = 'contactus_list.html'


class ContactUsCreateView(generic.CreateView):
    queryset = ContactUs.objects.all()
    template_name = 'contactus_create.html'
    form_class = ContactusForm
    success_url = reverse_lazy('currency:contactus_list')

    def form_valid(self, form):
        response = super().form_valid(form)

        send_contactus_mail.delay(self.object.email_to, self.object.message)

        return response


class RateListView(LoginRequiredMixin, FilterView):
    queryset = Rate.objects.all().select_related('source')
    template_name = 'rate_list.html'
    paginate_by = 10
    filterset_class = RateFilter

    def get_context_data(self, *args, **kwargs):
        context: dict = super().get_context_data(*args, **kwargs)
        filters_params = self.request.GET.copy()
        if self.page_kwarg in filters_params:
            del filters_params[self.page_kwarg]

        context['filters_params'] = filters_params.urlencode()
        context['page_size'] = self.get_paginate_by()
        return context

    def get_paginate_by(self, queryset=None):
        if 'page_size' in self.request.GET:
            paginate_by = self.request.GET['page_size']
        else:
            paginate_by = self.paginate_by

        return paginate_by


class RateCreateView(generic.CreateView):
    queryset = Rate.objects.all()
    template_name = 'rate_create.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')


class RateUpdateView(generic.UpdateView):
    queryset = Rate.objects.all()
    template_name = 'rate_update.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')


class RateDetailsView(generic.DeleteView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'


class RateDeleteView(generic.DeleteView):
    queryset = Rate.objects.all()
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rate_list')


class SourceListView(generic.ListView):
    queryset = Source.objects.all()
    template_name = 'source_list.html'


class SourceCreateView(generic.CreateView):
    queryset = Source.objects.all()
    template_name = 'source_create.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')


class SourceUpdateView(generic.UpdateView):
    queryset = Source.objects.all()
    template_name = 'source_update.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')


class SourceDetailsView(generic.DeleteView):
    queryset = Source.objects.all()
    template_name = 'source_details.html'


class SourceDeleteView(generic.DeleteView):
    queryset = Source.objects.all()
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source_list')


class UserProfileView(LoginRequiredMixin, generic.UpdateView):
    queryset = get_user_model().objects.all()
    template_name = 'my_profile.html'
    success_url = reverse_lazy('index')
    fields = (
        'first_name',
        'last_name',
        'avatar',
    )

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     queryset = queryset.filter(id=self.request.user.id)
    #     return queryset

    def get_object(self, queryset=None):
        return self.request.user

app/currency/templates/parts/navbar.html
{#<div>#}
{#    <a href="/">Home</a>#}
{##}
{#    {% if request.user.is_authenticated %}#}
{##}
{#        <a href="{% url 'currency:my_profile' %}">My Profile</a>#}
{#        <a href="{% url 'logout' %}">Logout</a>#}
{#        {{ request.user.email }}#}
{#    {% else %}#}
{#        <a href="{% url 'login' %}">Login</a>#}
{#        <a href="{% url 'accounts:signup' %}">SignUp</a>#}
{#    {% endif %}#}
{#</div>#}


<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      {% if request.user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'currency:my_profile' %}">{{ request.user.email }}</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
        </li>
          {% else %}
        <li class="collapse navbar-collapse">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="collapse navbar-collapse">
          <a class="nav-link active" href="{% url 'accounts:signup' %}">Sign Up</a>
        </li>
      </ul>
{% endif %}
    </div>
  </div>
</nav>

app/currency/templates/parts/pagination.html
<nav aria-label="Page navigation example">
<ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ filters_params }}">Previous</a></li>
        {% endif %}

        {% for page_num in page_obj.paginator.page_range %}
            <li class="page-item active"><a class="page-link" href="?page={{ page_num }}&{{ filters_params }}">{{ page_num }}</a></li>
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ filters_params }}">Next</a></li>
        {% endif %}
    </div>
  </ul>
</nav>