app/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('activate/<uuid:username>/', views.UserActivateView.as_view(), name='activate')


]

app/currency/urls.py
from django.urls import path
# from currency.views import contact_us_list
from app.currency import views

app_name = 'currency'

urlpatterns = [
    # path('rate/table/', rate_table),
    path('contactus/list/', views.ContactUsView.as_view(), name='contactus_list'),
    path('rate/list/', views.RateListView.as_view(), name='rate_list'),
    path('rate/create/', views.RateCreateView.as_view(), name='rate_create'),
    path('rate/update/<int:pk>/', views.RateUpdateView.as_view(), name='rate_update'),
    path('rate/delete/<int:pk>/', views.RateDeleteView.as_view(), name='rate_delete'),
    path('rate/details/<int:pk>/', views.RateDetailsView.as_view(), name='rate_details'),
    path('source/list/', views.SourceListView.as_view(), name='source_list'),
    path('source/create/', views.SourceCreateView.as_view(), name='source_create'),
    path('source/update/<int:pk>/', views.SourceUpdateView.as_view(), name='source_update'),
    path('source/details/<int:pk>/', views.SourceDetailsView.as_view(), name='source_details'),
    path('source/delete/<int:pk>/', views.SourceDeleteView.as_view(), name='source_delete'),
    path('contactus/create/', views.ContactUsCreateView.as_view(), name='contactus_create'),
    path('my-profile/', views.UserProfileView.as_view(), name='my_profile'),
    # path('change/password/', views.UserPasswordChangeView.as_view(), name='change_password'),
    # path('change/password/done/', views.UserPasswordChangeDoneView.as_view(), name='change_password_done'),


]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from app.currency import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('silk/', include('silk.urls', namespace='silk')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.v1.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from datetime import datetime
from django.db import models
from currency.model_choices import CurrencyType


class ContactUs(models.Model):
    email_from = models.EmailField(max_length=254)
    email_to = models.EmailField(max_length=254)
    subject = models.CharField(max_length=254)
    message = models.CharField(max_length=10_000)
    create = models.DateTimeField(auto_now_add=True)


def source_avatar(instance, filename):
    return 'source_avatar/{0}/{1}'.format(instance.id, filename)


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    bank_avatar = models.FileField(upload_to=source_avatar, default='bank.jpeg')


class Rate(models.Model):
    base_currency_type = models.CharField(max_length=3, choices=CurrencyType.choices,
                                          default=CurrencyType.CURRENCY_TYPE_UAH)
    currency_type = models.CharField(max_length=3, choices=CurrencyType.choices, null=True)
    sale = models.DecimalField(max_digits=10, decimal_places=4)
    buy = models.DecimalField(max_digits=10, decimal_places=4, null=True)
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE)
    created = models.DateTimeField(default=datetime.now)


class ResponseLog(models.Model):
    response_time = models.FloatField(max_length=10)
    request_method = models.CharField(max_length=12)
    query_params = models.CharField(max_length=20)
    ip = models.CharField(max_length=100)

app/currency/forms.py
from django import forms
from currency.models import Rate, Source, ContactUs


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'base_currency_type',
            'currency_type',
            'sale',
            'buy',
            'source',
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            "source_url",
            "name",
            'bank_avatar'
        )


class ContactusForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'email_from',
            'email_to',
            'subject',
            'message',
        )

app/currency/views.py
# from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from currency.filters import RateFilter
from currency.models import ContactUs, Rate, Source
from currency.forms import RateForm, SourceForm, ContactusForm
from django.views import generic
from django.urls import reverse_lazy
from django_filters.views import FilterView

from app.currency.tasks import send_contactus_mail


class IndexView(generic.TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rate_count'] = Rate.objects.count()
        context['source_count'] = Source.objects.count()
        return context


class ContactUsView(generic.ListView):
    queryset = ContactUs.objects.all()
    template_name = 'contactus_list.html'


class ContactUsCreateView(generic.CreateView):
    queryset = ContactUs.objects.all()
    template_name = 'contactus_create.html'
    form_class = ContactusForm
    success_url = reverse_lazy('currency:contactus_list')

    def form_valid(self, form):
        response = super().form_valid(form)

        send_contactus_mail.delay(self.object.email_to, self.object.message)

        return response


class RateListView(LoginRequiredMixin, FilterView):
    queryset = Rate.objects.all().select_related('source')
    template_name = 'rate_list.html'
    paginate_by = 10
    filterset_class = RateFilter

    def get_context_data(self, *args, **kwargs):
        context: dict = super().get_context_data(*args, **kwargs)
        filters_params = self.request.GET.copy()
        if self.page_kwarg in filters_params:
            del filters_params[self.page_kwarg]

        context['filters_params'] = filters_params.urlencode()
        context['page_size'] = self.get_paginate_by()
        return context

    def get_paginate_by(self, queryset=None):
        if 'page_size' in self.request.GET:
            paginate_by = self.request.GET['page_size']
        else:
            paginate_by = self.paginate_by

        return paginate_by


class RateCreateView(generic.CreateView):
    queryset = Rate.objects.all()
    template_name = 'rate_create.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')


class RateUpdateView(generic.UpdateView):
    queryset = Rate.objects.all()
    template_name = 'rate_update.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')


class RateDetailsView(generic.DeleteView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'


class RateDeleteView(generic.DeleteView):
    queryset = Rate.objects.all()
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rate_list')


class SourceListView(generic.ListView):
    queryset = Source.objects.all()
    template_name = 'source_list.html'


class SourceCreateView(generic.CreateView):
    queryset = Source.objects.all()
    template_name = 'source_create.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')


class SourceUpdateView(generic.UpdateView):
    queryset = Source.objects.all()
    template_name = 'source_update.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')


class SourceDetailsView(generic.DeleteView):
    queryset = Source.objects.all()
    template_name = 'source_details.html'


class SourceDeleteView(generic.DeleteView):
    queryset = Source.objects.all()
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source_list')


class UserProfileView(LoginRequiredMixin, generic.UpdateView):
    queryset = get_user_model().objects.all()
    template_name = 'my_profile.html'
    success_url = reverse_lazy('index')
    fields = (
        'first_name',
        'last_name',
        'avatar',
    )

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     queryset = queryset.filter(id=self.request.user.id)
    #     return queryset

    def get_object(self, queryset=None):
        return self.request.user

app/currency/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% for contact in contact_us_list %}
    <p>ID: {{ contact.id }}, Email from: {{ contact.email_from }}, Email to: {{ contact.email_to }},
    subject: {{ contact.subject }}, message: {{ contact.message }}, create: {{ contact.create }}</p>
{% endfor %}
</body>
</html>

app/currency/templates/base_html.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>

{% include 'parts/navbar.html' %}

{% block main_content %}
{% endblock main_content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
            crossorigin="anonymous"></script>
</body>
</html>

app/currency/templates/contactus_create.html
{% extends 'base_html.html' %}

{% block main_content %}
    {% load crispy_forms_tags %}
   ContactUs Create
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/contactus_list.html
{% extends 'base_html.html' %}

{% block main_content %}
    <div><a href="{% url 'currency:contactus_create' %}"> Create new contactus </a></div>

        <div class="container mt-3">
    <h2>Rate List</h2>
    <table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Email from</th>
        <th>Email to</th>
        <th>Message</th>

    </tr>
    </thead>
    <tbody>
    {% for contactus in contactus_list %}
        <tr>
            <td>{{ contactus.id }}</td>
            <td>{{ contactus.email_from  }}</td>
            <td>{{ contactus.email_to  }}</td>
            <td>{{ contactus.message  }}</td>
        </tr>
    {% endfor %}
{% endblock main_content %}

app/currency/templates/contactus_table.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<meta charset="utf-8">
<title>Table template</title>
<link rel="stylesheet" type="text/css" href="{% static 'minimal-table.css' %}">
<body>
<h1></h1>
<table>
    <caption>Contact Us</caption>
    <tr>
        <th scope="col"> ID</th>
        <th scope="col"> Email from</th>
        <th scope="col"> Email to</th>
        <th scope="col"> subject</th>
        <th scope="col"> message</th>
        <th scope="col"> create</th>
    </tr>
    {% for contact in contact_us_list %}
        <tr>
            <td>{{ contact.id }}</td>
            <td>{{ contact.email_from }}</td>
            <td>{{ contact.email_to }}</td>
            <td>{{ contact.subject }}</td>
            <td>{{ contact.message }}</td>
            <td>{{ contact.create }}</td>
        </tr>
    {% endfor %}
</table>


</body>
</html>

app/currency/templates/index.html
{% extends 'base_html.html' %}

{% block main_content %}
    <div>Currency Exchange Project</div>
    <div>Rate count : {{ rate_count }}</div>
    <div>Source count : {{ source_count }}</div>

<div>
    View List Rate: <a href="{% url 'currency:rate_list' %}"> Click Here</a>
{#    <p>View Table Rate: <a href="/rate/table/"> Click Here</a></p>#}
    <p>View Source List: <a href="{% url 'currency:source_list' %}"> Click Here</a></p>
    <p>View ContactUs List: <a href="{% url 'currency:contactus_list' %}"> Click Here</a></p>
</div>
{% endblock main_content %}

app/currency/templates/rate_create.html
{% extends 'base_html.html' %}

{% block main_content %}

    Rate Create
    <form method="post" >
        {% load crispy_forms_tags %}
        {% csrf_token %}

        {{ form|crispy }}
        <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/rate_delete.html
{% extends 'base_html.html' %}

{% block main_content %}

    Rate Delete

    <div>Delete object with id {{ object.id }}</div>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/rate_list.html
{% extends 'base_html.html' %}

{% block main_content %}
    <div>
        <a class="btn btn-primary"
           href="{% url 'currency:rate_create' %}"

           class="btn btn-primary active"
           role="button"> Create new rate </a>
    </div>

    <form method="get">
        {{ filter.form.as_p }}
        <label for="id-page_size">Items per page</label>
        <input name="page_size" id="id-page_size" value="{{ page_size }}" placeholder="3..100" type="number">
    <button type="submit">Filter</button>
    </form>
    <br>

    <div class="container mt-3">
        <h2>Rate List</h2>
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Sale</th>
                <th>Buy</th>
                <th>Base Currency Type</th>
                <th>Currency Type</th>
                <th>Source</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for rate in rate_list %}
                <tr>
                    <td>{{ rate.id }}</td>
                    <td>{{ rate.sale }}</td>
                    <td>{{ rate.buy }}</td>
                    <td>{{ rate.get_base_currency_type_display }}</td>
                    <td>{{ rate.get_currency_type_display }}</td>
                    <td>{{ rate.source.name }}
                        {% if rate.source.bank_avatar.url %}
                            <img src="{{ rate.source.bank_avatar.url }}" height="40" width="40">
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'currency:rate_details' rate.id %}"> View details </a>
                        <a href="{% url 'currency:rate_update' rate.id %}"> Edit </a>
                        <a href="{% url 'currency:rate_delete' rate.id %}"> Delete </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% include 'parts/pagination.html' %}

{% endblock main_content %}

app/currency/templates/rate_update.html
{% extends 'base_html.html' %}

{% block main_content %}

    Rate Update

    <form method="post" >
    {% load crispy_forms_tags %}
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/source_create.html
{% extends 'base_html.html' %}

{% block main_content %}
    {% load crispy_forms_tags %}
   Source Create
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/source_details.html
{% extends 'base_html.html' %}

{% block main_content %}

    Source Details


    <div>ID: {{ source_instance.id }}</div>
    <div>Source : {{ object.source_url }}</div>
    <div>Name : {{ object.name }}</div>
    <div>
        {% if source.bank_avatar.url %}
            <img src="{{ source.bank_avatar.url }}" height="40" width="40">
        {% endif %}
    </div>
{% endblock main_content %}

app/currency/templates/source_list.html
{% extends 'base_html.html' %}

{% block main_content %}
    <div>Currency Exchange Project</div>
    <div><a href="{% url 'currency:source_create' %}"> Create new source </a></div>

    <div class="container mt-3">
    <h2>Source List</h2>
    <table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Source url</th>
        <th>Name</th>
        <th>Actions</th>

    </tr>
    </thead>
    <tbody>
    {% for source in source_list %}
        <tr>
            <td>{{ source.id }}</td>
            <td>{{ source.source_url }}</td>
            <td>{{ source.name }}
                {% if source.bank_avatar.url %}
            <img src="{{ source.bank_avatar.url }}" height="40" width="40">
        {% endif %}
            </td>

            <td>
                <a href="{% url 'currency:source_details' source.id %}"> View details </a>
                <a href="{% url 'currency:source_update' source.id %}"> Edit </a>
                <a href="{% url 'currency:source_delete' source.id %}"> Delete</a>
            </td>
        </tr>
    {% endfor %}

{% endblock main_content %}

app/currency/templates/source_update.html
{% extends 'base_html.html' %}

{% block main_content %}

    Source Update
    <div>
        {% if source.bank_avatar.url %}
            <img src="{{ source.bank_avatar.url }}" height="40" width="40">
        {% endif %}
    </div>

    <form method="post" enctype="multipart/form-data">
    {% load crispy_forms_tags %}
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Send</button>
    </form>
{% endblock main_content %}